# Generated by Django 5.1.1 on 2024-11-19 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='saturation',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='blood_pressure',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='breath_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='heart_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
