# Generated by Django 5.1.1 on 2024-11-19 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vitalsign_date_recorded_vitalsign_saturation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
