# Generated by Django 5.1.1 on 2024-11-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vitalsign_date_recorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsign',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='vitalsign',
            name='saturation',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
