# Generated by Django 5.1.1 on 2024-11-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vitalsign_datdate_recorded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsign',
            old_name='datdate_recorded',
            new_name='date_recorded',
        ),
    ]
